# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#' propensity score matching roxygen from Rcpp
#' @return A list with two vectors (`x`, `y`).
#' @param x Numeric scalar. A vector of values we want to find matches to.
#' @examples
#' #creates 10 random poisson variables to calculates propensity scores
#' x<-rpois(n=10,lambda=3)
#' ps_match(x)
#' @export
ps_match <- function(x) {
    .Call(`_egpkg_ps_match`, x)
}

#' Hello world from Rcpp
#' @return A list with two vectors (`x`, `y`).
#' @examples
#' rcpp_hello_world()
#' @export
rcpp_hello_world <- function() {
    .Call(`_egpkg_rcpp_hello_world`)
}

